name: evaluacionmaquinas
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  connectivity_plus: ^6.1.3
  supabase_flutter: ^2.6.3
  image_picker: ^1.0.7
  curved_navigation_bar: ^1.0.3
  equatable: ^2.0.5
  go_router: ^15.0.0
  app_links: ^6.4.0
  logger: ^2.2.0
  flutter_native_splash: ^2.4.6
  envied: ^1.1.1
  shared_preferences: ^2.0.8
  diacritic: 0.1.6
  qr_flutter: 4.1.0
  screenshot: ^3.0.0
  image: ^4.5.4
  open_filex: ^4.7.0 # Mejor soporte para desktop
  path: 1.9.1 # Para manejo correcto de rutas


  #PDF
  path_provider: ^2.0.11
  pdf: ^3.10.8
  syncfusion_flutter_pdfviewer: 29.1.38   #flutter_pdfview: ^1.2.7

  fluttertoast: ^8.2.12

  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0 #para formatear fechas
  flutter_dotenv: ^5.0.2


  expandable: ^5.0.1
  expandable_menu: 0.0.5

  permission_handler: ^12.0.0+1
  file_picker: ^10.1.2
  flutter_file_dialog: ^3.0.0
  share_plus: ^10.0.0
  intl_utils: ^2.8.10
  flutter_launcher_icons: ^0.14.3
  #http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4
  build_runner: ^2.4.9
  flutter_lints: ^5.0.0
  envied_generator: ^1.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 24
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env
  fonts:
     - family: Manrope
       fonts:
         - asset: assets/fonts/Gill-Sans.otf
         - asset: assets/fonts/Gill-Sans-Bold.otf



