name: evaluacionmaquinas
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.3.3
  image_picker: ^1.0.7
  curved_navigation_bar: ^1.0.3
  google_nav_bar: ^5.0.6 #QUITAR
  convert: ^3.1.1 #QUITAR
  equatable: ^2.0.5
  go_router: ^14.0.2
  uni_links: ^0.5.1
  logger: ^2.2.0
  flutter_native_splash: ^2.4.0
  envied: ^0.5.4+1
  shared_preferences: ^2.0.8
  diacritic: 0.1.6
  qr_flutter: 4.1.0
  screenshot: ^2.5.0
  image: ^4.0.21

  #PDF
  flutter_pdfview: ^1.2.7
  path_provider: ^2.0.11
  pdf: ^3.10.8


  fluttertoast: ^8.2.8

  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1 #para formatear fechas


  expandable: ^5.0.1
  expandable_menu: 0.0.5


  permission_handler: ^11.0.0
  file_picker: ^6.0.0
  flutter_file_dialog: ^3.0.0
  share_plus: ^7.0.2
  flutter_map: any
  latlong2: ^0.9.1
  intl_utils: ^2.4.2
  flutter_launcher_icons: ^0.14.1
  #http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.9

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - lib/images/
  fonts:
     - family: Manrope
       fonts:
         - asset: lib/theme/fonts/Gill-Sans.otf
